using System.Text.Json;
using SubtitleVideoTool.Core;

namespace SubtitleVideoTool.Core.Tests;

/// <summary>
/// Exercised against the real output of
/// <c>yt-dlp -J --skip-download</c>, captured from YouTube rather than written
/// by hand, so the parser is held to what yt-dlp actually emits.
/// </summary>
public class VideoProbeTests
{
    private static readonly Lazy<VideoInfo> RealVideo = new(() =>
        VideoProbe.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "TestData", "probe-rickroll.json"))));

    [Fact]
    public void ReadsTheVideoIdentity()
    {
        var info = RealVideo.Value;

        Assert.Equal("dQw4w9WgXcQ", info.Id);
        Assert.Contains("Never Gonna Give You Up", info.Title);
        Assert.Equal(TimeSpan.FromSeconds(213), info.Duration);
        Assert.Equal("3:33", info.DurationText);
    }

    [Fact]
    public void OffersOnlyTheHeightsTheVideoActuallyHas()
    {
        var heights = RealVideo.Value.Qualities.Select(q => q.Height).ToArray();

        Assert.Equal([2160, 1440, 1080, 720, 480, 360, 240, 144], heights);
    }

    [Fact]
    public void MarksTheHeightsThatHaveNoH264()
    {
        var byHeight = RealVideo.Value.Qualities.ToDictionary(q => q.Height);

        // Above 1080p this video exists only as VP9/AV1 — the design puts a
        // compatibility note next to exactly these.
        Assert.False(byHeight[2160].HasH264);
        Assert.False(byHeight[1440].HasH264);
        Assert.True(byHeight[1080].HasH264);
        Assert.True(byHeight[720].HasH264);
    }

    [Fact]
    public void SizesAreReportedWhereKnownAndOmittedWhereNot()
    {
        var qualities = RealVideo.Value.Qualities;

        Assert.All(qualities, quality =>
        {
            if (quality.ApproximateBytes is { } bytes)
            {
                Assert.True(bytes > 0);
                Assert.StartsWith("about ", quality.SizeText);
            }
            else
            {
                // The column stays empty rather than showing a guess or a dash.
                Assert.Equal(string.Empty, quality.SizeText);
            }
        });

        Assert.Contains(qualities, q => q.ApproximateBytes is > 0);
    }

    [Fact]
    public void EnglishIsRecognisedAsHumanWrittenOnThisVideo()
    {
        var subtitle = RealVideo.Value.Subtitle;

        Assert.Equal(EnglishSubtitleKind.HumanWritten, subtitle.Kind);
        Assert.True(subtitle.IsAvailable);
        Assert.Equal("Written by a person", subtitle.Headline);
    }

    [Fact]
    public void FrameRateIsPrintedOnlyAboveThirty()
    {
        Assert.Equal("720p", new QualityOption { Height = 720, Fps = 25 }.Label);
        Assert.Equal("720p", new QualityOption { Height = 720, Fps = 30 }.Label);
        Assert.Equal("720p 60 fps", new QualityOption { Height = 720, Fps = 60 }.Label);
        Assert.Equal("1080p", new QualityOption { Height = 1080 }.Label);
    }

    [Theory]
    [InlineData("subtitles", EnglishSubtitleKind.HumanWritten)]
    [InlineData("automatic_captions", EnglishSubtitleKind.AutoGenerated)]
    public void EnglishTrackIsClassifiedByWhereItLives(string property, EnglishSubtitleKind expected)
    {
        var json = $$"""
            { "{{property}}": { "en": [ { "ext": "srt", "url": "https://example.test/track" } ] } }
            """;

        Assert.Equal(expected, VideoProbe.Parse(json).Subtitle.Kind);
    }

    [Fact]
    public void ATranslatedTrackIsToldApartByItsTlangParameter()
    {
        var json = """
            {
              "language": "ja",
              "automatic_captions": {
                "en": [ { "ext": "srt", "url": "https://example.test/track?lang=ja&tlang=en" } ]
              }
            }
            """;

        var subtitle = VideoProbe.Parse(json).Subtitle;

        Assert.Equal(EnglishSubtitleKind.AutoTranslated, subtitle.Kind);
        Assert.Equal("Japanese", subtitle.TranslatedFrom);
        Assert.Equal("Machine-translated from Japanese", subtitle.Headline);
    }

    [Fact]
    public void RegionalEnglishVariantsStillCount()
    {
        var json = """
            { "subtitles": { "en-US": [ { "ext": "srt", "url": "https://example.test/t" } ] } }
            """;

        Assert.Equal(EnglishSubtitleKind.HumanWritten, VideoProbe.Parse(json).Subtitle.Kind);
    }

    [Fact]
    public void NoEnglishIsNotAnError()
    {
        var json = """
            {
              "subtitles": { "de": [ { "ext": "srt", "url": "https://example.test/t" } ] },
              "automatic_captions": { "fr": [ { "ext": "srt", "url": "https://example.test/t?tlang=fr" } ] }
            }
            """;

        var subtitle = VideoProbe.Parse(json).Subtitle;

        Assert.Equal(EnglishSubtitleKind.None, subtitle.Kind);
        Assert.False(subtitle.IsAvailable);
        Assert.Equal("This video has no English subtitles", subtitle.Headline);
        Assert.Equal("— the video downloads on its own", subtitle.Detail);
    }

    [Fact]
    public void AProbeWithNoFormatsYieldsNoQualitiesRatherThanThrowing()
    {
        var info = VideoProbe.Parse("""{ "id": "x", "title": "No formats" }""");

        Assert.Empty(info.Qualities);
        Assert.Equal(EnglishSubtitleKind.None, info.Subtitle.Kind);
        Assert.Equal(string.Empty, info.DurationText);
    }

    [Fact]
    public void MalformedJsonBecomesAReadableProbeFailure()
    {
        // yt-dlp printing an error where the JSON document should be must not
        // put "invalid JSON literal ... BytePositionInLine" in front of the user.
        var error = Assert.Throws<ProbeException>(() => VideoProbe.Parse("ERROR: Video unavailable"));

        Assert.Equal("YouTube's answer could not be read.", error.Message);
        Assert.IsAssignableFrom<JsonException>(error.InnerException);
    }

    [Theory]
    [InlineData("ja", "Japanese")]
    [InlineData("fa", "Persian")]
    [InlineData("pt-BR", "Portuguese (Brazil)")]
    [InlineData("iw", "Hebrew")]
    [InlineData(null, null)]
    public void LanguageCodesBecomeReadableNames(string? code, string? expected)
    {
        Assert.Equal(expected, VideoProbe.DescribeLanguage(code));
    }

    [Fact]
    public void AnUnknownLanguageCodeKeepsItsRawForm()
    {
        Assert.Equal("zzz", VideoProbe.DescribeLanguage("zzz"));
    }

    [Theory]
    [InlineData(512L * 1024 * 1024, "512 MB")]
    [InlineData(9L * 1024 * 1024, "9 MB")]
    [InlineData(1536L, "2 KB")]
    public void SizesReadTheWayTheDesignWritesThem(long bytes, string expected)
    {
        Assert.Equal(expected, DownloadFailure.FormatSize(bytes));
    }
}
