using System.Globalization;
using System.Text.Json;

namespace SubtitleVideoTool.Core;

public enum EnglishSubtitleKind
{
    /// <summary>No English subtitle of any kind. Not an error — the video downloads on its own.</summary>
    None,

    /// <summary>A track a person wrote. The only case the design paints green.</summary>
    HumanWritten,

    /// <summary>Speech recognition on English audio.</summary>
    AutoGenerated,

    /// <summary>Machine translation of a non-English video. The roughest kind.</summary>
    AutoTranslated,
}

public sealed record EnglishSubtitle
{
    public EnglishSubtitleKind Kind { get; init; } = EnglishSubtitleKind.None;

    /// <summary>Display name of the source language, when the track was translated.</summary>
    public string? TranslatedFrom { get; init; }

    public bool IsAvailable => Kind != EnglishSubtitleKind.None;

    /// <summary>The bold half of the line, exactly as the design words it.</summary>
    public string Headline => Kind switch
    {
        EnglishSubtitleKind.HumanWritten => "Written by a person",
        EnglishSubtitleKind.AutoGenerated => "Made by speech recognition",
        EnglishSubtitleKind.AutoTranslated => TranslatedFrom is { Length: > 0 } from
            ? $"Machine-translated from {from}"
            : "Machine-translated from another language",
        _ => "This video has no English subtitles",
    };

    /// <summary>The grey half of the line.</summary>
    public string Detail => Kind switch
    {
        EnglishSubtitleKind.HumanWritten => "— the best kind this app can get",
        EnglishSubtitleKind.AutoGenerated => "— readable, with mistakes in names and numbers",
        EnglishSubtitleKind.AutoTranslated => "— the roughest kind. Expect to edit it before burning.",
        _ => "— the video downloads on its own",
    };
}

public sealed record QualityOption
{
    public int Height { get; init; }
    public int? Fps { get; init; }

    /// <summary>Null when the probe did not report a size. The design leaves the column empty rather than guessing.</summary>
    public long? ApproximateBytes { get; init; }

    /// <summary>False above 1080p on most videos: only VP9/AV1 exist there.</summary>
    public bool HasH264 { get; init; }

    /// <summary>"720p 60 fps" — frame rate is printed only above 30.</summary>
    public string Label => Fps is > 30 ? $"{Height}p {Fps} fps" : $"{Height}p";

    public string SizeText => ApproximateBytes is > 0
        ? "about " + DownloadFailure.FormatSize(ApproximateBytes.Value)
        : string.Empty;
}

public sealed record VideoInfo
{
    public string Id { get; init; } = string.Empty;
    public string Title { get; init; } = string.Empty;
    public TimeSpan? Duration { get; init; }
    public string? ThumbnailUrl { get; init; }
    public IReadOnlyList<QualityOption> Qualities { get; init; } = [];
    public EnglishSubtitle Subtitle { get; init; } = new();

    /// <summary>"3:33 · 8 qualities available", the design's summary line.</summary>
    public string DurationText => Duration is { } d
        ? d.TotalHours >= 1
            ? d.ToString(@"h\:mm\:ss", CultureInfo.InvariantCulture)
            : d.ToString(@"m\:ss", CultureInfo.InvariantCulture)
        : string.Empty;
}

/// <summary>
/// Reads the JSON that <c>yt-dlp -J --skip-download</c> prints. Everything the
/// download tab shows before a download starts comes from here.
/// </summary>
/// <summary>
/// yt-dlp answered, but not with JSON we can read. Usually means it printed an
/// error where the document should have been.
/// </summary>
public sealed class ProbeException(string message, Exception? inner = null) : Exception(message, inner);

public static class VideoProbe
{
    public static VideoInfo Parse(string json)
    {
        JsonDocument document;
        try
        {
            document = JsonDocument.Parse(json);
        }
        catch (JsonException error)
        {
            // Never let a reader exception reach the failure card: it would put
            // "invalid JSON literal ... BytePositionInLine" in front of the user.
            throw new ProbeException("YouTube's answer could not be read.", error);
        }

        using (document)
        {
            return Read(document.RootElement);
        }
    }

    private static VideoInfo Read(JsonElement root)
    {

        return new VideoInfo
        {
            Id = GetString(root, "id") ?? string.Empty,
            Title = GetString(root, "title") ?? string.Empty,
            Duration = GetDouble(root, "duration") is { } seconds and > 0
                ? TimeSpan.FromSeconds(seconds)
                : null,
            ThumbnailUrl = GetString(root, "thumbnail"),
            Qualities = ReadQualities(root),
            Subtitle = ReadEnglishSubtitle(root),
        };
    }

    /// <summary>
    /// One entry per distinct height, best first. A height the video does not
    /// have is never offered.
    /// </summary>
    private static List<QualityOption> ReadQualities(JsonElement root)
    {
        if (!root.TryGetProperty("formats", out var formats) || formats.ValueKind != JsonValueKind.Array)
        {
            return [];
        }

        var videoFormats = new List<(int Height, int? Fps, long? Size, string Vcodec)>();
        long? bestAudioBytes = null;

        foreach (var format in formats.EnumerateArray())
        {
            var vcodec = GetString(format, "vcodec");
            var acodec = GetString(format, "acodec");
            var size = GetLong(format, "filesize") ?? GetLong(format, "filesize_approx");

            var hasVideo = vcodec is { Length: > 0 } && vcodec != "none";
            var hasAudio = acodec is { Length: > 0 } && acodec != "none";

            if (!hasVideo && hasAudio)
            {
                // Audio-only. The smallest usable one is what gets merged in.
                if (size is > 0 && (bestAudioBytes is null || size < bestAudioBytes))
                {
                    bestAudioBytes = size;
                }

                continue;
            }

            if (!hasVideo)
            {
                continue;
            }

            var height = GetInt(format, "height");
            if (height is not > 0)
            {
                continue;
            }

            var fps = GetDouble(format, "fps");
            videoFormats.Add((height.Value, fps is > 0 ? (int)Math.Round(fps.Value) : null, size, vcodec!));
        }

        return videoFormats
            .GroupBy(f => f.Height)
            .Select(group =>
            {
                var h264 = group.Where(f => f.Vcodec.StartsWith("avc1", StringComparison.OrdinalIgnoreCase)).ToList();

                // The app's selector prefers H.264, so size the option the same
                // way it will actually be downloaded.
                var preferred = h264.Count > 0 ? h264 : [.. group];
                var videoBytes = preferred
                    .Where(f => f.Size is > 0)
                    .Select(f => f.Size!.Value)
                    .DefaultIfEmpty(0)
                    .Min();

                return new QualityOption
                {
                    Height = group.Key,
                    Fps = group.Max(f => f.Fps),
                    HasH264 = h264.Count > 0,
                    ApproximateBytes = videoBytes > 0 ? videoBytes + (bestAudioBytes ?? 0) : null,
                };
            })
            .OrderByDescending(option => option.Height)
            .ToList();
    }

    /// <summary>
    /// Verified against real probe output: a human-written track is an "en" key
    /// under <c>subtitles</c>; auto-generated and auto-translated are both "en"
    /// under <c>automatic_captions</c>, told apart by whether the track URL
    /// carries a <c>tlang=</c> parameter.
    /// </summary>
    private static EnglishSubtitle ReadEnglishSubtitle(JsonElement root)
    {
        if (FindEnglishTrack(root, "subtitles") is not null)
        {
            return new EnglishSubtitle { Kind = EnglishSubtitleKind.HumanWritten };
        }

        var automatic = FindEnglishTrack(root, "automatic_captions");
        if (automatic is null)
        {
            return new EnglishSubtitle { Kind = EnglishSubtitleKind.None };
        }

        var translated = automatic.Value.EnumerateArray().Any(track =>
            GetString(track, "url") is { } url &&
            url.Contains("tlang=", StringComparison.OrdinalIgnoreCase));

        if (!translated)
        {
            return new EnglishSubtitle { Kind = EnglishSubtitleKind.AutoGenerated };
        }

        return new EnglishSubtitle
        {
            Kind = EnglishSubtitleKind.AutoTranslated,
            TranslatedFrom = DescribeLanguage(GetString(root, "language")),
        };
    }

    /// <summary>Matches "en" and regional variants such as "en-US".</summary>
    private static JsonElement? FindEnglishTrack(JsonElement root, string propertyName)
    {
        if (!root.TryGetProperty(propertyName, out var tracks) || tracks.ValueKind != JsonValueKind.Object)
        {
            return null;
        }

        foreach (var track in tracks.EnumerateObject())
        {
            var code = track.Name;
            var isEnglish = code.Equals("en", StringComparison.OrdinalIgnoreCase) ||
                            code.StartsWith("en-", StringComparison.OrdinalIgnoreCase);

            if (isEnglish && track.Value.ValueKind == JsonValueKind.Array)
            {
                return track.Value;
            }
        }

        return null;
    }

    /// <summary>
    /// "ja" becomes "Japanese". Legacy codes that .NET does not know keep their
    /// raw form rather than producing "Unknown Language (iw)".
    /// </summary>
    public static string? DescribeLanguage(string? code)
    {
        if (string.IsNullOrWhiteSpace(code))
        {
            return null;
        }

        // Codes YouTube still emits that predate the current ISO assignments.
        var normalised = code.ToLowerInvariant() switch
        {
            "iw" => "he",
            "in" => "id",
            "ji" => "yi",
            _ => code,
        };

        try
        {
            var culture = CultureInfo.GetCultureInfo(normalised);
            var name = culture.EnglishName;
            if (!name.Contains("Unknown Language", StringComparison.OrdinalIgnoreCase))
            {
                // "Japanese (Japan)" reads better as "Japanese" in a sentence.
                var bracket = name.IndexOf(" (", StringComparison.Ordinal);
                return bracket > 0 && culture.TwoLetterISOLanguageName == normalised
                    ? name[..bracket]
                    : name;
            }
        }
        catch (CultureNotFoundException)
        {
            // Fall through to the raw code.
        }

        return code;
    }

    private static string? GetString(JsonElement element, string name) =>
        element.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.String
            ? value.GetString()
            : null;

    private static double? GetDouble(JsonElement element, string name) =>
        element.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.Number
            ? value.GetDouble()
            : null;

    private static int? GetInt(JsonElement element, string name) =>
        element.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.Number
            ? value.GetInt32()
            : null;

    private static long? GetLong(JsonElement element, string name) =>
        element.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.Number
            ? value.GetInt64()
            : null;
}
